---
# syntax - https://github.com/redhat-plumbers-in-action/advanced-issue-labeler#policy

policy:
  - template: [01-issue-sc.yml, 02-issue-webapp.yml]
    section:
      - id: [environment]
        label:
          - name: "env:pre-produzione"
            keys: ['pre-produzione']
          - name: "env:produzione"
            keys: ['produzione']     
      - id: [service]
        label:
          #R001 - Servizi cooperativi allegati
          - name: "R001 allegati"
            keys: ['R001 - Servizi cooperativi allegati']
          - name: "R002 certificazioni"
            keys: ['R002 - Servizi cooperativi certificazioni']
          - name: "R003 comunicazioni"
            keys: ['R003 - Servizi cooperativi comunicazioni']
          - name: "R004 consultazione evento"
            keys: ['R004 - Servizi cooperativi consultazione anagrafe per gestione anagrafica evento di stato civile']
          - name: "R005 consultazione"
            keys: ['R005 - Servizi cooperativi consultazione']
          #firme
          - name: "R006 firma dichiarante"
            keys: ['R006 - Servizi cooperativi firma dichiarante']
          - name: "R007 firma USC"
            keys: ['R007 - Servizi cooperativi firma ufficiale di stato civile']                         
          - name: "R012"
            keys: ['R012 - Servizi cooperativi firma elettronica del dichiarante']
          - name: "R008 notifiche"
            keys: ['R008 - Servizi cooperativi notifiche']
          - name: "R009 validazione"
            keys: ['R009 - Servizi cooperativi validazione evento']
          - name: "anteprima"
            keys: ['R010 - Servizi cooperativi anteprima']
          #- name: "R011 cancellazione"
          #  keys: ['R011 - Servizi cooperativi per la cancellazione logica di un atto']
          #- name: "R013 rettifica"
          #  keys: ['R013 - Servizi cooperativi per la validazione della rettifica']
          #- name: "R014 validità anagrafe"
          #  keys: ['R014 - Servizi cooperativi per la gestione data di validità verso anagrafe']
          #- name: "R901 decodifica"
          #  keys: ['R901 - Servizio di configurazione per il reperibimento delle tabelle di decodifica']