blank_issues_enabled: false
contact_links:
  - name: Issue Servizi Cooperativi ANSC
    url: https://github.com/italia/ansc/issues
    about: Problemi che si verificano utilizzando i servizi cooperativi ANSC (R001, R002, etc)
  - name: Issue WebApp ANSC
    url: https://github.com/italia/ansc/issues
    about: Problemi che si verificano utilizzando l'applicazione https://anscweb.anpr.interno.it/ansc  
  - name: Domande o supporto sull'utilizzo dei servizi
    url: https://github.com/italia/ansc/discussions/new
    about: Quesiti inerenti l'utilizzo dei servizi
  - name: Domande o supporto sull'utilizzo della webapp
    url: https://github.com/italia/ansc/discussions/new
    about: Quesiti inerenti l'utilizzo dell'applicazione https://anscweb.anpr.interno.it/ansc   
  - name: Dove trovo la documentazione?
    url: https://github.com/italia/ansc/blob/main/docs/index.md
    about: Documentazione